# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zulus/Projects/GitProj/progbase2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zulus/Projects/GitProj/progbase2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zulus/Projects/GitProj/progbase2/CMakeFiles /home/zulus/Projects/GitProj/progbase2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zulus/Projects/GitProj/progbase2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named university

# Build rule for target.
university: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 university
.PHONY : university

# fast build rule for target.
university/fast:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/build
.PHONY : university/fast

#=============================================================================
# Target rules for targets named a.out

# Build rule for target.
a.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 a.out
.PHONY : a.out

# fast build rule for target.
a.out/fast:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/build
.PHONY : a.out/fast

#=============================================================================
# Target rules for targets named a.out_coverage

# Build rule for target.
a.out_coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 a.out_coverage
.PHONY : a.out_coverage

# fast build rule for target.
a.out_coverage/fast:
	$(MAKE) -f CMakeFiles/a.out_coverage.dir/build.make CMakeFiles/a.out_coverage.dir/build
.PHONY : a.out_coverage/fast

src/collection/dlList.o: src/collection/dlList.c.o

.PHONY : src/collection/dlList.o

# target to build an object file
src/collection/dlList.c.o:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/src/collection/dlList.c.o
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/collection/dlList.c.o
.PHONY : src/collection/dlList.c.o

src/collection/dlList.i: src/collection/dlList.c.i

.PHONY : src/collection/dlList.i

# target to preprocess a source file
src/collection/dlList.c.i:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/src/collection/dlList.c.i
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/collection/dlList.c.i
.PHONY : src/collection/dlList.c.i

src/collection/dlList.s: src/collection/dlList.c.s

.PHONY : src/collection/dlList.s

# target to generate assembly for a file
src/collection/dlList.c.s:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/src/collection/dlList.c.s
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/collection/dlList.c.s
.PHONY : src/collection/dlList.c.s

src/collection/dlNode.o: src/collection/dlNode.c.o

.PHONY : src/collection/dlNode.o

# target to build an object file
src/collection/dlNode.c.o:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/src/collection/dlNode.c.o
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/collection/dlNode.c.o
.PHONY : src/collection/dlNode.c.o

src/collection/dlNode.i: src/collection/dlNode.c.i

.PHONY : src/collection/dlNode.i

# target to preprocess a source file
src/collection/dlNode.c.i:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/src/collection/dlNode.c.i
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/collection/dlNode.c.i
.PHONY : src/collection/dlNode.c.i

src/collection/dlNode.s: src/collection/dlNode.c.s

.PHONY : src/collection/dlNode.s

# target to generate assembly for a file
src/collection/dlNode.c.s:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/src/collection/dlNode.c.s
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/collection/dlNode.c.s
.PHONY : src/collection/dlNode.c.s

src/lecturer.o: src/lecturer.c.o

.PHONY : src/lecturer.o

# target to build an object file
src/lecturer.c.o:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/src/lecturer.c.o
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/lecturer.c.o
.PHONY : src/lecturer.c.o

src/lecturer.i: src/lecturer.c.i

.PHONY : src/lecturer.i

# target to preprocess a source file
src/lecturer.c.i:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/src/lecturer.c.i
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/lecturer.c.i
.PHONY : src/lecturer.c.i

src/lecturer.s: src/lecturer.c.s

.PHONY : src/lecturer.s

# target to generate assembly for a file
src/lecturer.c.s:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/src/lecturer.c.s
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/lecturer.c.s
.PHONY : src/lecturer.c.s

src/student.o: src/student.c.o

.PHONY : src/student.o

# target to build an object file
src/student.c.o:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/src/student.c.o
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/student.c.o
.PHONY : src/student.c.o

src/student.i: src/student.c.i

.PHONY : src/student.i

# target to preprocess a source file
src/student.c.i:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/src/student.c.i
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/student.c.i
.PHONY : src/student.c.i

src/student.s: src/student.c.s

.PHONY : src/student.s

# target to generate assembly for a file
src/student.c.s:
	$(MAKE) -f CMakeFiles/university.dir/build.make CMakeFiles/university.dir/src/student.c.s
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/src/student.c.s
.PHONY : src/student.c.s

test/main.o: test/main.c.o

.PHONY : test/main.o

# target to build an object file
test/main.c.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/test/main.c.o
.PHONY : test/main.c.o

test/main.i: test/main.c.i

.PHONY : test/main.i

# target to preprocess a source file
test/main.c.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/test/main.c.i
.PHONY : test/main.c.i

test/main.s: test/main.c.s

.PHONY : test/main.s

# target to generate assembly for a file
test/main.c.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/test/main.c.s
.PHONY : test/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... university"
	@echo "... a.out"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... a.out_coverage"
	@echo "... src/collection/dlList.o"
	@echo "... src/collection/dlList.i"
	@echo "... src/collection/dlList.s"
	@echo "... src/collection/dlNode.o"
	@echo "... src/collection/dlNode.i"
	@echo "... src/collection/dlNode.s"
	@echo "... src/lecturer.o"
	@echo "... src/lecturer.i"
	@echo "... src/lecturer.s"
	@echo "... src/student.o"
	@echo "... src/student.i"
	@echo "... src/student.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

